export const CUBING_DATA:string[] = [
  // PLL
  "PLL	01Ub	M2' U' M U2' M' U' M2'	(M2' U' M U2' M' U' M2') *2",
  "PLL	02Ua	M2' U M U2 M' U M2'	(M2' U M U2 M' U M2') *2",
  "PLL	03H	M2' U' M2' U2' M2' U' M2'	M2' U' M2' U2' M2' U' M2'",
  "PLL	04Ab	x (L U' L) D2 (L' U L) D2 L2 x'	(x (L U' L) D2 (L' U L) D2 L2 x') *2",
  "PLL	05Aa	x L2' D2 (L' U' L) D2 (L' U L') x'	(x L2' D2 (L' U' L) D2 (L' U L') x') *2",
  "PLL	06T	(R U R' U') R' F R2 U' R' U' (R U R') F'	(R U R' U') R' F R2 U' R' U' (R U R') F'",
  "PLL	07Nb	(L' U R' U2 L U' R) (L' U R' U2 L U' R) U'	((L' U R' U2 L U' R) (L' U R' U2 L U' R) U') *2",
  "PLL	08Na	(R U' L U2' R' U L') (R U' L U2' R' U L') U	(R U' L U2' R' U L') (R U' L U2' R' U L') U",
  "PLL	09Z	(M2' U') (M2' U') M' (U2' M2' U2') M' U2'	(M2' U') (M2' U') M' (U2' M2' U2') M' U2'",
  "PLL	10E	x' (L' U L D') (L' U' L D) (L' U' L D') (L' U L D) x	x' (L' U L D') (L' U' L D) (L' U' L D') (L' U L D) x",
  "PLL	11V	(R' U R U') (R' f' U' R) U2' (R' U' R U') R' f R	(R' U R U') (R' f' U' R) U2' (R' U' R U') R' f R",
  "PLL	12F	R' U' F' (R U R' U') R' F R2 (U' R' U') (R U R') U R	R' U' F' (R U R' U') R' F R2 (U' R' U') (R U R') U R",
  "PLL	13Rb	R2 F R (U R U' R') F' R U2' R' U2' R U	R2 F R (U R U' R') F' R U2' R' U2' R U",
  "PLL	14Ra	(R U' R' U') (R U R D) (R' U' R D') (R' U2' R') U'	(R U' R' U') (R U R D) (R' U' R D') (R' U2' R') U'",
  "PLL	15Jb	(R U R') F' (R U R' U') R' F R2 U' R' U'	(R U R') F' (R U R' U') R' F R2 U' R' U'",
  "PLL	16Ja	(L' U' L) F (L' U' L U) L F' L2' U L U	(L' U' L) F (L' U' L U) L F' L2' U L U",
  "PLL	17Y	F (R U' R' U') (R U R') F' (R U R' U') (R' F R F')	F (R U' R' U') (R U R') F' (R U R' U') (R' F R F')",
  "PLL	18Gd	(R U R') (U' D) R2 U' R U' R' U R' U R2 D'	((R U R') (U' D) R2 U' R U' R' U R' U R2 D)*3",
  "PLL	19Gc	R2 U' R U' R U R' U R2 (D' U) (R U' R') D	(R2 U' R U' R U R' U R2 (D' U) (R U' R') D) *3",
  "PLL	20Gb	(R' U' R) (U D') R2 U R' U R U' R U' R2 D	((R' U' R) (U D') R2 U R' U R U' R U' R2 D) *3",
  "PLL	21Ga	R2 U R' U R' U' R U' R2 (D U') (R' U R) D'	(R2 U R' U R' U' R U' R2 (D U') (R' U R) D) *3",
  // OLL
  "OLL	01	R U2' R' U' (R U R' U') R U' R' 	R U2' R' U' (R U R' U') R U' R' ",
  "OLL	02	R U2' R2 U' R2 U' R2 U2' R	R U2' R2 U' R2 U' R2 U2' R",
  "OLL	03	R' F' R B' R' F R B	(R' F' R B' R' F R B) *2",
  "OLL	04	B' R' F' R B R' F R	(B' R' F' R B R' F R) *2",
  "OLL	05	(R2 D' R) U2' (R' D R) U2' R	((R2 D' R) U2' (R' D R) U2' R) *2",
  "OLL	06	(L' U' L) U' L' U2' L	((L' U' L) U' L' U2' L y`) *2",
  "OLL	07	(R U R') U R U2 R'	((R U R') U R U2 R' y) *2",
];
